source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'TheMovieDB' do
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Alamofire', '~> 3.3'
pod 'AlamofireImage', '~> 2.0'
pod 'SDWebImage', '~>3.8'

end






